import { Router } from 'express'
import { githubRepoSchema } from '../utils/github-url'

export const generateRouter = Router()

generateRouter.post('/', async (req, res) => {
  try {
    const parsed = githubRepoSchema.parse(req.body)

    res.json({
      success: true,
      repoUrl: parsed.repoUrl,
      docs: {
        readme: '# Generated README\\n\\nThis documentation will be generated by Ollama in Phase 4.',
        installation: '## Installation\\n\\nComing soon...',
        environment: '## Environment Variables\\n\\nComing soon...',
        deployment: '## Deployment\\n\\nComing soon...',
        apiDocs: '## API Documentation\\n\\nComing soon...',
      },
    })
  } catch (error: any) {
    res.status(400).json({
      error: {
        message: error.errors?.[0]?.message || 'Invalid request',
        code: 'INVALID_REPO_URL',
      },
    })
  }
})